### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ASauceyApple** [natethemaker/Kahoot-Flooder#1]
I did everything it said and what popped up was

Error: Cannot find module 'C:\Users\blank\blank\blank\Kahoot-Flooder-main\flood.js'
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:769:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []

I don't know what's wrong

**Comment by natethemaker** [comment]
at what stage did the error happen?

**Comment by ASauceyApple** [comment]
It happened when I typed in mode flood.js

**Comment by natethemaker** [comment]
it is `node flood.js` rather than `mode index.js`

**Comment by ASauceyApple** [comment]
it was autocorrect but that's what i mean

**Comment by natethemaker** [comment]
I have updated the read me test the new method or replit to see if it works

**Comment by natethemaker** [comment]
i am closing this issue
